// This is a static mock dataset for development/demo purposes.
export const mockCars = [
  {
    city_mpg: 22,
    class: "sedan",
    combination_mpg: 25,
    cylinders: 4,
    displacement: 2.0,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 30,
    make: "honda",
    model: "civic",
    transmission: "a",
    year: 2022,
  },
  {
    city_mpg: 20,
    class: "suv",
    combination_mpg: 23,
    cylinders: 6,
    displacement: 3.5,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 27,
    make: "toyota",
    model: "rav4",
    transmission: "a",
    year: 2021,
  },
  {
    city_mpg: 120,
    class: "hatchback",
    combination_mpg: 118,
    cylinders: 0,
    displacement: 0,
    drive: "fwd",
    fuel_type: "electricity",
    highway_mpg: 112,
    make: "tesla",
    model: "model 3",
    transmission: "a",
    year: 2023,
  },
  {
    city_mpg: 18,
    class: "truck",
    combination_mpg: 16,
    cylinders: 8,
    displacement: 5.0,
    drive: "rwd",
    fuel_type: "gas",
    highway_mpg: 20,
    make: "ford",
    model: "f-150",
    transmission: "a",
    year: 2020,
  },
  // --- Additional 46 cars ---
  { city_mpg: 25, class: "sedan", combination_mpg: 28, cylinders: 4, displacement: 2.5, drive: "fwd", fuel_type: "gas", highway_mpg: 35, make: "hyundai", model: "elantra", transmission: "a", year: 2022 },
  { city_mpg: 24, class: "sedan", combination_mpg: 27, cylinders: 4, displacement: 2.4, drive: "fwd", fuel_type: "gas", highway_mpg: 34, make: "kia", model: "optima", transmission: "a", year: 2021 },
  { city_mpg: 21, class: "suv", combination_mpg: 24, cylinders: 6, displacement: 3.6, drive: "awd", fuel_type: "gas", highway_mpg: 28, make: "jeep", model: "grand cherokee", transmission: "a", year: 2020 },
  { city_mpg: 19, class: "suv", combination_mpg: 22, cylinders: 6, displacement: 3.7, drive: "awd", fuel_type: "gas", highway_mpg: 25, make: "nissan", model: "pathfinder", transmission: "a", year: 2019 },
  { city_mpg: 30, class: "hatchback", combination_mpg: 32, cylinders: 4, displacement: 1.8, drive: "fwd", fuel_type: "gas", highway_mpg: 38, make: "volkswagen", model: "golf", transmission: "a", year: 2022 },
  { city_mpg: 17, class: "truck", combination_mpg: 15, cylinders: 8, displacement: 5.7, drive: "rwd", fuel_type: "gas", highway_mpg: 19, make: "ram", model: "1500", transmission: "a", year: 2021 },
  { city_mpg: 23, class: "sedan", combination_mpg: 26, cylinders: 4, displacement: 2.0, drive: "fwd", fuel_type: "gas", highway_mpg: 33, make: "mazda", model: "mazda3", transmission: "a", year: 2020 },
  { city_mpg: 22, class: "suv", combination_mpg: 25, cylinders: 4, displacement: 2.5, drive: "awd", fuel_type: "gas", highway_mpg: 31, make: "subaru", model: "forester", transmission: "a", year: 2022 },
  { city_mpg: 27, class: "sedan", combination_mpg: 30, cylinders: 4, displacement: 2.0, drive: "fwd", fuel_type: "gas", highway_mpg: 37, make: "chevrolet", model: "malibu", transmission: "a", year: 2021 },
  { city_mpg: 16, class: "truck", combination_mpg: 14, cylinders: 8, displacement: 6.2, drive: "rwd", fuel_type: "gas", highway_mpg: 18, make: "gmc", model: "sierra", transmission: "a", year: 2020 },
  { city_mpg: 15, class: "suv", combination_mpg: 17, cylinders: 8, displacement: 5.3, drive: "awd", fuel_type: "gas", highway_mpg: 21, make: "chevrolet", model: "tahoe", transmission: "a", year: 2019 },
  { city_mpg: 28, class: "hatchback", combination_mpg: 30, cylinders: 4, displacement: 1.6, drive: "fwd", fuel_type: "gas", highway_mpg: 36, make: "ford", model: "focus", transmission: "a", year: 2018 },
  { city_mpg: 32, class: "sedan", combination_mpg: 35, cylinders: 4, displacement: 1.5, drive: "fwd", fuel_type: "gas", highway_mpg: 40, make: "honda", model: "accord", transmission: "a", year: 2023 },
  { city_mpg: 14, class: "truck", combination_mpg: 12, cylinders: 8, displacement: 6.4, drive: "rwd", fuel_type: "gas", highway_mpg: 16, make: "dodge", model: "ram 2500", transmission: "a", year: 2017 },
  { city_mpg: 26, class: "suv", combination_mpg: 29, cylinders: 4, displacement: 2.0, drive: "awd", fuel_type: "gas", highway_mpg: 34, make: "hyundai", model: "tucson", transmission: "a", year: 2022 },
  { city_mpg: 29, class: "sedan", combination_mpg: 32, cylinders: 4, displacement: 2.0, drive: "fwd", fuel_type: "gas", highway_mpg: 39, make: "kia", model: "forte", transmission: "a", year: 2021 },
  { city_mpg: 20, class: "suv", combination_mpg: 23, cylinders: 6, displacement: 3.3, drive: "awd", fuel_type: "gas", highway_mpg: 27, make: "mazda", model: "cx-9", transmission: "a", year: 2020 },
  { city_mpg: 24, class: "hatchback", combination_mpg: 27, cylinders: 4, displacement: 1.8, drive: "fwd", fuel_type: "gas", highway_mpg: 33, make: "toyota", model: "corolla", transmission: "a", year: 2019 },
  { city_mpg: 31, class: "sedan", combination_mpg: 34, cylinders: 4, displacement: 1.4, drive: "fwd", fuel_type: "gas", highway_mpg: 41, make: "chevrolet", model: "cruze", transmission: "a", year: 2018 },
  { city_mpg: 18, class: "truck", combination_mpg: 15, cylinders: 8, displacement: 5.0, drive: "rwd", fuel_type: "gas", highway_mpg: 19, make: "toyota", model: "tundra", transmission: "a", year: 2017 },
  { city_mpg: 33, class: "hatchback", combination_mpg: 36, cylinders: 4, displacement: 1.2, drive: "fwd", fuel_type: "gas", highway_mpg: 43, make: "mitsubishi", model: "mirage", transmission: "a", year: 2022 },
  { city_mpg: 27, class: "suv", combination_mpg: 30, cylinders: 4, displacement: 2.4, drive: "awd", fuel_type: "gas", highway_mpg: 35, make: "honda", model: "cr-v", transmission: "a", year: 2021 },
  { city_mpg: 22, class: "sedan", combination_mpg: 25, cylinders: 4, displacement: 2.0, drive: "fwd", fuel_type: "gas", highway_mpg: 31, make: "nissan", model: "altima", transmission: "a", year: 2020 },
  { city_mpg: 19, class: "truck", combination_mpg: 16, cylinders: 8, displacement: 5.3, drive: "rwd", fuel_type: "gas", highway_mpg: 20, make: "chevrolet", model: "silverado", transmission: "a", year: 2019 },
  { city_mpg: 35, class: "hatchback", combination_mpg: 38, cylinders: 4, displacement: 1.0, drive: "fwd", fuel_type: "gas", highway_mpg: 45, make: "ford", model: "fiesta", transmission: "a", year: 2018 },
  { city_mpg: 30, class: "sedan", combination_mpg: 33, cylinders: 4, displacement: 1.6, drive: "fwd", fuel_type: "gas", highway_mpg: 40, make: "hyundai", model: "accent", transmission: "a", year: 2022 },
  { city_mpg: 28, class: "suv", combination_mpg: 31, cylinders: 4, displacement: 2.0, drive: "awd", fuel_type: "gas", highway_mpg: 36, make: "mazda", model: "cx-5", transmission: "a", year: 2021 },
  { city_mpg: 21, class: "truck", combination_mpg: 18, cylinders: 6, displacement: 3.5, drive: "rwd", fuel_type: "gas", highway_mpg: 23, make: "ford", model: "ranger", transmission: "a", year: 2020 },
  { city_mpg: 25, class: "hatchback", combination_mpg: 28, cylinders: 4, displacement: 1.5, drive: "fwd", fuel_type: "gas", highway_mpg: 34, make: "honda", model: "fit", transmission: "a", year: 2019 },
  { city_mpg: 34, class: "sedan", combination_mpg: 37, cylinders: 4, displacement: 1.3, drive: "fwd", fuel_type: "gas", highway_mpg: 44, make: "toyota", model: "yaris", transmission: "a", year: 2018 },
  { city_mpg: 29, class: "suv", combination_mpg: 32, cylinders: 4, displacement: 2.0, drive: "awd", fuel_type: "gas", highway_mpg: 37, make: "subaru", model: "outback", transmission: "a", year: 2022 },
  { city_mpg: 20, class: "truck", combination_mpg: 17, cylinders: 8, displacement: 5.7, drive: "rwd", fuel_type: "gas", highway_mpg: 21, make: "ram", model: "2500", transmission: "a", year: 2021 },
  { city_mpg: 23, class: "hatchback", combination_mpg: 26, cylinders: 4, displacement: 1.6, drive: "fwd", fuel_type: "gas", highway_mpg: 32, make: "kia", model: "rio", transmission: "a", year: 2020 },
  { city_mpg: 36, class: "sedan", combination_mpg: 39, cylinders: 4, displacement: 1.2, drive: "fwd", fuel_type: "gas", highway_mpg: 47, make: "hyundai", model: "ioniq", transmission: "a", year: 2019 },
  { city_mpg: 31, class: "suv", combination_mpg: 34, cylinders: 4, displacement: 2.0, drive: "awd", fuel_type: "gas", highway_mpg: 39, make: "mazda", model: "cx-30", transmission: "a", year: 2018 },
  { city_mpg: 27, class: "truck", combination_mpg: 24, cylinders: 6, displacement: 3.6, drive: "rwd", fuel_type: "gas", highway_mpg: 29, make: "chevrolet", model: "colorado", transmission: "a", year: 2022 },
  { city_mpg: 22, class: "hatchback", combination_mpg: 25, cylinders: 4, displacement: 1.8, drive: "fwd", fuel_type: "gas", highway_mpg: 31, make: "toyota", model: "prius", transmission: "a", year: 2021 },
  { city_mpg: 24, class: "sedan", combination_mpg: 27, cylinders: 4, displacement: 2.0, drive: "fwd", fuel_type: "gas", highway_mpg: 33, make: "nissan", model: "sentra", transmission: "a", year: 2020 },
  { city_mpg: 20, class: "suv", combination_mpg: 23, cylinders: 6, displacement: 3.5, drive: "awd", fuel_type: "gas", highway_mpg: 27, make: "honda", model: "pilot", transmission: "a", year: 2019 },
  { city_mpg: 28, class: "hatchback", combination_mpg: 31, cylinders: 4, displacement: 1.4, drive: "fwd", fuel_type: "gas", highway_mpg: 36, make: "chevrolet", model: "spark", transmission: "a", year: 2018 },
  { city_mpg: 33, class: "sedan", combination_mpg: 36, cylinders: 4, displacement: 1.2, drive: "fwd", fuel_type: "gas", highway_mpg: 43, make: "mitsubishi", model: "lancer", transmission: "a", year: 2017 },
  { city_mpg: 26, class: "truck", combination_mpg: 23, cylinders: 6, displacement: 3.5, drive: "rwd", fuel_type: "gas", highway_mpg: 28, make: "ford", model: "maverick", transmission: "a", year: 2022 },
  { city_mpg: 21, class: "hatchback", combination_mpg: 24, cylinders: 4, displacement: 1.6, drive: "fwd", fuel_type: "gas", highway_mpg: 29, make: "kia", model: "soul", transmission: "a", year: 2021 },
  { city_mpg: 19, class: "suv", combination_mpg: 22, cylinders: 6, displacement: 3.7, drive: "awd", fuel_type: "gas", highway_mpg: 25, make: "nissan", model: "murano", transmission: "a", year: 2020 },
  { city_mpg: 25, class: "sedan", combination_mpg: 28, cylinders: 4, displacement: 2.5, drive: "fwd", fuel_type: "gas", highway_mpg: 35, make: "toyota", model: "camry", transmission: "a", year: 2019 },
  { city_mpg: 30, class: "hatchback", combination_mpg: 33, cylinders: 4, displacement: 1.6, drive: "fwd", fuel_type: "gas", highway_mpg: 38, make: "hyundai", model: "veloster", transmission: "a", year: 2018 },
  { city_mpg: 22, class: "truck", combination_mpg: 19, cylinders: 6, displacement: 3.3, drive: "rwd", fuel_type: "gas", highway_mpg: 25, make: "nissan", model: "frontier", transmission: "a", year: 2017 },
  { city_mpg: 28, class: "sedan", combination_mpg: 31, cylinders: 4, displacement: 2.0, drive: "fwd", fuel_type: "gas", highway_mpg: 36, make: "mazda", model: "mazda6", transmission: "a", year: 2022 },
  { city_mpg: 24, class: "hatchback", combination_mpg: 27, cylinders: 4, displacement: 1.8, drive: "fwd", fuel_type: "gas", highway_mpg: 33, make: "toyota", model: "matrix", transmission: "a", year: 2021 },
  { city_mpg: 20, class: "suv", combination_mpg: 23, cylinders: 6, displacement: 3.5, drive: "awd", fuel_type: "gas", highway_mpg: 27, make: "ford", model: "explorer", transmission: "a", year: 2020 },
  { city_mpg: 32, class: "sedan", combination_mpg: 35, cylinders: 4, displacement: 1.5, drive: "fwd", fuel_type: "gas", highway_mpg: 40, make: "honda", model: "insight", transmission: "a", year: 2019 },
  { city_mpg: 18, class: "truck", combination_mpg: 15, cylinders: 8, displacement: 5.0, drive: "rwd", fuel_type: "gas", highway_mpg: 19, make: "chevrolet", model: "avalanche", transmission: "a", year: 2018 },
  { city_mpg: 27, class: "hatchback", combination_mpg: 30, cylinders: 4, displacement: 1.6, drive: "fwd", fuel_type: "gas", highway_mpg: 35, make: "kia", model: "ceed", transmission: "a", year: 2017 },
  { city_mpg: 23, class: "suv", combination_mpg: 26, cylinders: 4, displacement: 2.0, drive: "awd", fuel_type: "gas", highway_mpg: 32, make: "mazda", model: "cx-3", transmission: "a", year: 2016 },
  { city_mpg: 25, class: "sedan", combination_mpg: 28, cylinders: 4, displacement: 2.5, drive: "fwd", fuel_type: "gas", highway_mpg: 35, make: "nissan", model: "maxima", transmission: "a", year: 2015 },
  { city_mpg: 30, class: "hatchback", combination_mpg: 33, cylinders: 4, displacement: 1.6, drive: "fwd", fuel_type: "gas", highway_mpg: 38, make: "hyundai", model: "getz", transmission: "a", year: 2014 },
  { city_mpg: 22, class: "truck", combination_mpg: 19, cylinders: 6, displacement: 3.3, drive: "rwd", fuel_type: "gas", highway_mpg: 25, make: "toyota", model: "hilux", transmission: "a", year: 2013 },
  { city_mpg: 28, class: "sedan", combination_mpg: 31, cylinders: 4, displacement: 2.0, drive: "fwd", fuel_type: "gas", highway_mpg: 36, make: "mazda", model: "mazda2", transmission: "a", year: 2012 },
  { city_mpg: 24, class: "hatchback", combination_mpg: 27, cylinders: 4, displacement: 1.8, drive: "fwd", fuel_type: "gas", highway_mpg: 33, make: "toyota", model: "auris", transmission: "a", year: 2011 },
  { city_mpg: 20, class: "suv", combination_mpg: 23, cylinders: 6, displacement: 3.5, drive: "awd", fuel_type: "gas", highway_mpg: 27, make: "honda", model: "element", transmission: "a", year: 2010 },
  { city_mpg: 28, class: "hatchback", combination_mpg: 31, cylinders: 4, displacement: 1.4, drive: "fwd", fuel_type: "gas", highway_mpg: 36, make: "chevrolet", model: "aveo", transmission: "a", year: 2009 },
  { city_mpg: 33, class: "sedan", combination_mpg: 36, cylinders: 4, displacement: 1.2, drive: "fwd", fuel_type: "gas", highway_mpg: 43, make: "mitsubishi", model: "galant", transmission: "a", year: 2008 },
  { city_mpg: 26, class: "truck", combination_mpg: 23, cylinders: 6, displacement: 3.5, drive: "rwd", fuel_type: "gas", highway_mpg: 28, make: "ford", model: "courier", transmission: "a", year: 2007 },
  { city_mpg: 21, class: "hatchback", combination_mpg: 24, cylinders: 4, displacement: 1.6, drive: "fwd", fuel_type: "gas", highway_mpg: 29, make: "kia", model: "picanto", transmission: "a", year: 2006 },
  { city_mpg: 19, class: "suv", combination_mpg: 22, cylinders: 6, displacement: 3.7, drive: "awd", fuel_type: "gas", highway_mpg: 25, make: "nissan", model: "x-trail", transmission: "a", year: 2005 },
  { city_mpg: 25, class: "sedan", combination_mpg: 28, cylinders: 4, displacement: 2.5, drive: "fwd", fuel_type: "gas", highway_mpg: 35, make: "toyota", model: "avalon", transmission: "a", year: 2004 },
  { city_mpg: 30, class: "hatchback", combination_mpg: 33, cylinders: 4, displacement: 1.6, drive: "fwd", fuel_type: "gas", highway_mpg: 38, make: "hyundai", model: "excel", transmission: "a", year: 2003 },
  { city_mpg: 22, class: "truck", combination_mpg: 19, cylinders: 6, displacement: 3.3, drive: "rwd", fuel_type: "gas", highway_mpg: 25, make: "nissan", model: "navara", transmission: "a", year: 2002 },
  { city_mpg: 28, class: "sedan", combination_mpg: 31, cylinders: 4, displacement: 2.0, drive: "fwd", fuel_type: "gas", highway_mpg: 36, make: "mazda", model: "mazda323", transmission: "a", year: 2001 },
  { city_mpg: 24, class: "hatchback", combination_mpg: 27, cylinders: 4, displacement: 1.8, drive: "fwd", fuel_type: "gas", highway_mpg: 33, make: "toyota", model: "starlet", transmission: "a", year: 2000 }
];
